/// DO NOT EDIT.  This file is auto-generated by make_testdata.py
#pragma once

#include <vector>
#include <string>
#include <array>

#include "libvideoio/types/ImageSize.h"

typedef unsigned char BYTE;

const int NUM_TEST_IMAGES=3;
extern const std::array<std::string, NUM_TEST_IMAGES> TestImages;

const int SNIPPET_SIZE=4;
typedef std::array< BYTE, SNIPPET_SIZE > ImageSnippetRow;
typedef std::array< ImageSnippetRow, SNIPPET_SIZE > ImageSnippet;

extern const std::array< ImageSnippet, NUM_TEST_IMAGES > ImageSnippets;

const size_t TestImageWidth = 640;
const size_t TestImageHeight = 480;
const libvideoio::ImageSize TestImageSize( TestImageWidth, TestImageHeight );

std::vector<BYTE> TestImage( int i );
